-- ============================================================
-- La Trattoria - Carga de carta completa
-- ============================================================
USE latrattoria;

ALTER TABLE categoria MODIFY COLUMN nombre VARCHAR(20) NOT NULL;

SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM DetallePedido;
DELETE FROM Plato;
DELETE FROM categoria;
ALTER TABLE Plato AUTO_INCREMENT = 1;
ALTER TABLE categoria AUTO_INCREMENT = 1;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO categoria (id_categoria, nombre) VALUES
  (1, 'entrante'),
  (2, 'pasta'),
  (3, 'pizza'),
  (4, 'carne'),
  (5, 'postre'),
  (6, 'bebida');

INSERT INTO Plato (nombre, descripcion, precio, imagen, disponibilidad, id_categoria) VALUES
  ('Bufala e Pomodori', 'Mozzarella de Búfala fresca y tomates con aceite de oliva virgen extra, orégano y albahaca', 13.50, 'https://loremflickr.com/400/300/buffalo,mozzarella,tomato?lock=1', 'activo', 1),
  ('Insalata Primavera', 'Espinacas frescas, rúcula, manzana verde, queso Feta, nueces y crema de vinagre balsámico', 11.50, 'https://loremflickr.com/400/300/spinach,salad,apple?lock=2', 'activo', 1),
  ('Provolone alla Mediterranea', 'Queso provolone a la plancha con tomates cherry, aceitunas y orégano', 10.00, 'https://loremflickr.com/400/300/provolone,cheese,grilled?lock=3', 'activo', 1),
  ('Insalata Trattoria', 'Vinagreta de mango, lechuga, espinacas, aguacate, tomatitos, queso feta y langostinos cocidos', 14.00, 'https://loremflickr.com/400/300/salad,prawns,mango?lock=4', 'activo', 1),
  ('Insalata Mista', 'Lechuga, tomates, cebolla, zanahoria, maíz, aceitunas negras, huevo duro y melva', 11.00, 'https://loremflickr.com/400/300/mixed,salad,tuna?lock=5', 'activo', 1),
  ('Burrata fritta con Mortadella e Pistacchio', 'Burrata frita en costra envuelta en mortadela IGP y pistacho', 12.00, 'https://loremflickr.com/400/300/burrata,mortadella,pistachio?lock=6', 'activo', 1),
  ('Insalata di Gamberi agli Agrumi', 'Langostinos cocidos, piña, cherry, zanahoria, cebolla morada, vinagreta de cítricos y jengibre', 10.00, 'https://loremflickr.com/400/300/prawns,citrus,salad?lock=7', 'activo', 1),
  ('Calamaro Fritto', 'Calamar de potera frito, tierno y del típico sabor dulce', 14.00, 'https://loremflickr.com/400/300/fried,calamari,squid?lock=8', 'activo', 1),
  ('Tartare di Tonno Rosso di Tarifa', 'Tartare de Atún Rojo Mackintosh de Tarifa (150 g)', 18.00, 'https://loremflickr.com/400/300/tuna,tartare,red?lock=9', 'activo', 1),
  ('Carpaccio di Filetto Trattoria', 'Carpaccio de solomillo con escamas de trufa negra y Parmigiano', 18.00, 'https://loremflickr.com/400/300/beef,carpaccio,truffle?lock=10', 'activo', 1),
  ('Carpaccio di Filetto Classico', 'Carpaccio de solomillo con rúcula y Parmigiano', 14.00, 'https://loremflickr.com/400/300/beef,carpaccio,rocket?lock=11', 'activo', 1),
  ('Focaccia Oro del Estrecho', 'Focaccia con crema de burrata y tartare de Atún Rojo Mackintosh', 18.00, 'https://loremflickr.com/400/300/focaccia,burrata,tuna?lock=12', 'activo', 1),
  ('Focaccia Jabugo', 'Focaccia caliente con surtido ibérico de bellota y queso Payoyo', 18.00, 'https://loremflickr.com/400/300/focaccia,iberico,ham?lock=13', 'activo', 1),
  ('Montanara (entrante)', 'Pizza frita napolitana de 10-12 cm con salsa de tomate y Parmigiano', 7.00, 'https://loremflickr.com/400/300/fried,pizza,napoletana?lock=14', 'activo', 1),
  ('Calzoncino Fritto', 'Pequeño calzone frito relleno de ricotta, salame, provola ahumada y tomate', 5.50, 'https://loremflickr.com/400/300/calzone,fried,italian?lock=15', 'activo', 1),
  ('Lasagna Bolognese al forno a legna', 'Lasaña de carne casera cocida al horno de leña', 13.00, 'https://loremflickr.com/400/300/lasagna,bolognese?lock=16', 'activo', 2),
  ('Lasagna Trattoria', 'Lasaña con bechamel, ragú blanco de cerdo, provola y puerros', 13.00, 'https://loremflickr.com/400/300/lasagna,white,sauce?lock=17', 'activo', 2),
  ('Gnocchetti Funghi e Gorgonzola', 'Ñoquis con setas silvestres y Gorgonzola', 12.00, 'https://loremflickr.com/400/300/gnocchi,mushrooms,gorgonzola?lock=18', 'activo', 2),
  ('Tagliatelle al Ragú Bolognese', 'Tagliatelle con salsa boloñesa casera', 11.50, 'https://loremflickr.com/400/300/tagliatelle,bolognese?lock=19', 'activo', 2),
  ('Carbonara Autentica', 'Yema de huevo, pimienta, Guanciale Romano y Pecorino Romano', 12.00, 'https://loremflickr.com/400/300/carbonara,pasta,roman?lock=20', 'activo', 2),
  ('Linguine al Pesto Genovese', 'Linguine con pesto de albahaca, piñones y Parmigiano', 12.00, 'https://loremflickr.com/400/300/linguine,pesto,genovese?lock=21', 'activo', 2),
  ('Tagliatelle al Tartufo e Formaggio', 'Tagliatelle con salsa de trufa y queso', 16.50, 'https://loremflickr.com/400/300/tagliatelle,truffle,cheese?lock=22', 'activo', 2),
  ('Risotto ai Sapori di Autunno', 'Risotto con speck, setas, crema de calabaza y Parmigiano', 15.00, 'https://loremflickr.com/400/300/risotto,pumpkin,speck?lock=23', 'activo', 2),
  ('Gnocchetti cremosi al Pesto Rosso', 'Ñoquis con pesto de tomates secos, albahaca, almendras, pistachos y ricotta fresca', 12.50, 'https://loremflickr.com/400/300/gnocchi,red,pesto?lock=24', 'activo', 2),
  ('Spaghetti alla Puttanesca Nobile', 'Tomates Pacchettelle del Vesuvio, aceitunas Taggiasche, alcaparras y anchoas del Cantábrico', 14.00, 'https://loremflickr.com/400/300/spaghetti,puttanesca,olives?lock=25', 'activo', 2),
  ('Mezzi Paccheri con Gamberi e Pesto di Pistacchi', 'Mezzi paccheri con gambas y pesto de pistachos', 16.00, 'https://loremflickr.com/400/300/paccheri,prawns,pistachio?lock=26', 'activo', 2),
  ('Linguine ai Frutti di Mare', 'Linguine con almejas, mejillones, gambas y calamar (con o sin tomate)', 14.50, 'https://loremflickr.com/400/300/linguine,seafood,clams?lock=27', 'activo', 2),
  ('Ravioloni Ricotta e Spinaci', 'Ravioli rellenos de ricotta y espinacas con salsa de tomate San Marzano y pesto', 14.00, 'https://loremflickr.com/400/300/ravioli,ricotta,spinach?lock=28', 'activo', 2),
  ('Mezze Lune con Caprino e Fichi', 'Medias lunas rellenas de queso de cabra e higos con crema de Pecorino y miel', 14.50, 'https://loremflickr.com/400/300/pasta,goat,cheese,figs?lock=29', 'activo', 2),
  ('Fagottini Formaggio e Pera', 'Saquitos rellenos de queso y pera con salsa de nueces', 14.00, 'https://loremflickr.com/400/300/fagottini,pear,cheese?lock=30', 'activo', 2),
  ('Tortelli alla Zucca', 'Tortelli rellenos de calabaza con panceta ahumada, romero y Parmigiano', 15.00, 'https://loremflickr.com/400/300/tortelli,pumpkin,bacon?lock=31', 'activo', 2),
  ('Lunette al Tartufo', 'Pasta rellena de trufa y ricotta con bechamel al parmesano y crujiente de jamón', 14.50, 'https://loremflickr.com/400/300/pasta,truffle,bechamel?lock=32', 'activo', 2),
  ('Gnocchetti Gamberi e Zafferano', 'Ñoquis con gambas, calabacines, azafrán y un toque de nata', 14.50, 'https://loremflickr.com/400/300/gnocchi,shrimp,saffron?lock=33', 'activo', 2),
  ('Fettuccine ai Gamberi Rossi di Garrucha', 'Tagliatelle finas en bisque de gambas rojas y su tartare', 19.00, 'https://loremflickr.com/400/300/fettuccine,red,prawns?lock=34', 'activo', 2),
  ('Pasta al Pomodoro per Bambini', 'Pasta con salsa de tomate o aceite de oliva para niños', 8.00, 'https://loremflickr.com/400/300/pasta,tomato,kids?lock=35', 'activo', 2),
  ('Marinara', 'Tomate, ajo, orégano, albahaca', 8.00, 'https://loremflickr.com/400/300/marinara,pizza,garlic?lock=36', 'activo', 3),
  ('Margherita', 'Tomate, mozzarella, albahaca', 10.00, 'https://loremflickr.com/400/300/margherita,pizza,basil?lock=37', 'activo', 3),
  ('Margherita DOC', 'Tomates San Marzano, mozzarella de búfala, albahaca', 13.00, 'https://loremflickr.com/400/300/pizza,buffalo,mozzarella?lock=38', 'activo', 3),
  ('Napoletana 2.0', 'Mozzarella, tomates Pacchettelle del Vesuvio, aceitunas Taggiasche, alcaparras y anchoas', 14.50, 'https://loremflickr.com/400/300/pizza,napoletana,anchovies?lock=39', 'activo', 3),
  ('Capricciosa', 'Tomate, mozzarella, jamón cocido, champiñones, alcachofas y anchoas', 12.50, 'https://loremflickr.com/400/300/pizza,capricciosa,artichoke?lock=40', 'activo', 3),
  ('Quattro Formaggi', 'Tomate, mozzarella, Gorgonzola, Parmigiano y provolone curado', 12.00, 'https://loremflickr.com/400/300/pizza,four,cheese?lock=41', 'activo', 3),
  ('Primavera', 'Tomates frescos, mozzarella de búfala, jamón serrano, rúcula y escamas de Parmigiano', 14.50, 'https://loremflickr.com/400/300/pizza,prosciutto,arugula?lock=42', 'activo', 3),
  ('Diego', 'Tomate, provola ahumada, guanciale, cebolla y parmesano', 11.00, 'https://loremflickr.com/400/300/pizza,guanciale,onion?lock=43', 'activo', 3),
  ('Montanara (pizza)', 'Tomate, mozzarella, bacon ahumado, patatas al horno, champiñones y parmesano', 13.00, 'https://loremflickr.com/400/300/pizza,bacon,potatoes?lock=44', 'activo', 3),
  ('Prosciutto e Funghi', 'Tomate, mozzarella, jamón cocido y champiñones', 11.50, 'https://loremflickr.com/400/300/pizza,ham,mushrooms?lock=45', 'activo', 3),
  ('Trattoria', 'Tomate, mozzarella de búfala, jamón serrano y setas silvestres', 14.50, 'https://loremflickr.com/400/300/pizza,mushrooms,prosciutto?lock=46', 'activo', 3),
  ('Cipolla e Salamino', 'Tomate, mozzarella, cebolla y salami picante', 11.50, 'https://loremflickr.com/400/300/pizza,salami,onion?lock=47', 'activo', 3),
  ('Almadraba', 'Tomate, mozzarella, atún y cebolla', 11.50, 'https://loremflickr.com/400/300/pizza,tuna,onion?lock=48', 'activo', 3),
  ('Calabrese', 'Tomate, provola ahumada, salami picante, n''dujia y Pecorino picante', 13.00, 'https://loremflickr.com/400/300/pizza,nduja,calabrese?lock=49', 'activo', 3),
  ('Rustica', 'Tomate, mozzarella, salame italiano y ricotta di fuscella', 12.00, 'https://loremflickr.com/400/300/pizza,salami,ricotta?lock=50', 'activo', 3),
  ('La Bufala Fresca', 'Tomate, albahaca y mozzarella de búfala fresca (no horneada)', 13.00, 'https://loremflickr.com/400/300/pizza,buffalo,fresh?lock=51', 'activo', 3),
  ('Carbonara Pizza', 'Provola ahumada, Guanciale Romano, Carbocrema con yema, sal, pimienta y Pecorino', 13.00, 'https://loremflickr.com/400/300/pizza,carbonara,egg?lock=52', 'activo', 3),
  ('Calzone Classico', 'Tomate, mozzarella, jamón cocido, champiñones y ricotta', 11.50, 'https://loremflickr.com/400/300/calzone,classic,ham?lock=53', 'activo', 3),
  ('Vegetariana', 'Mozzarella, crema de calabacines, berenjena, pimientos, espinacas y tomates', 13.00, 'https://loremflickr.com/400/300/pizza,vegetables,eggplant?lock=54', 'activo', 3),
  ('Vegana', 'Crema de calabaza, albahaca, aceitunas, cebolla, orégano y n''dujia picante vegana', 13.00, 'https://loremflickr.com/400/300/pizza,vegan,pumpkin?lock=55', 'activo', 3),
  ('Tartufo', 'Mozzarella, crema de trufa, setas Boletus, rúcula y speck', 17.00, 'https://loremflickr.com/400/300/pizza,truffle,boletus?lock=56', 'activo', 3),
  ('Li Mortazzi Tua', 'Mozzarella, burrata, pesto de pistacho, mortadela, pesto de albahaca y pistachos', 16.50, 'https://loremflickr.com/400/300/pizza,mortadella,pistachio?lock=57', 'activo', 3),
  ('Crudo e Bufala', 'Cherry semisecos, mozzarella de búfala, jamón serrano y parmesano', 14.50, 'https://loremflickr.com/400/300/pizza,buffalo,prosciutto?lock=58', 'activo', 3),
  ('Pesto e Melanzane', 'Tomate, mozzarella, pesto de albahaca, berenjenas fritas y bacon ahumado', 12.50, 'https://loremflickr.com/400/300/pizza,pesto,eggplant?lock=59', 'activo', 3),
  ('Black Angus', 'Burrata, carpaccio de Black Angus ahumado, trufa, rúcula, cherry y zeste de limón', 18.00, 'https://loremflickr.com/400/300/pizza,blackangus,truffle?lock=60', 'activo', 3),
  ('Da Impazzire', 'Borde relleno de provola ahumada, tomate, cebolla, salami picante y gorgonzola', 16.00, 'https://loremflickr.com/400/300/pizza,stuffed,crust?lock=61', 'activo', 3),
  ('Bombazza', 'Borde relleno de ricotta, crema de calabaza, cherry semisecos, provola ahumada, pesto y parmesano', 16.00, 'https://loremflickr.com/400/300/pizza,ricotta,pumpkin?lock=62', 'activo', 3),
  ('La Porchetta', 'Mousse de pistachos y Gorgonzola, cherry semisecos, provola ahumada y porchetta italiana', 16.00, 'https://loremflickr.com/400/300/porchetta,pizza,italian?lock=63', 'activo', 3),
  ('Pastrami', 'Pastrami de Black Angus, mozzarella, Gorgonzola, setas silvestres, Parmigiano y nueces', 14.00, 'https://loremflickr.com/400/300/pizza,pastrami,gorgonzola?lock=64', 'activo', 3),
  ('Payoyo & Cotto', 'Crema de queso Payoyo, jamón cocido artesanal, alcachofas confitadas y crema de setas', 15.00, 'https://loremflickr.com/400/300/pizza,payoyo,artichoke?lock=65', 'activo', 3),
  ('Olé Andalucía', 'Crema de queso Payoyo, queso Andazul, higos secos, jamón ibérico y nueces', 17.00, 'https://loremflickr.com/400/300/pizza,andalusia,iberico?lock=66', 'activo', 3),
  ('McTominay', 'Provola ahumada, jamón ibérico, alcachofas confitadas, patatas al horno y huevo poché', 17.00, 'https://loremflickr.com/400/300/pizza,iberico,potatoes?lock=67', 'activo', 3),
  ('Cecina de León', 'Mozzarella de búfala, cecina de León, crema de setas, Parmigiano y huevo poché', 18.00, 'https://loremflickr.com/400/300/pizza,cecina,mushroom?lock=68', 'activo', 3),
  ('Tagliata di Vacca Rúcula e Parmigiano', 'Lomo bajo de vaca fileteado con rúcula y Parmigiano', 20.00, 'https://loremflickr.com/400/300/tagliata,beef,parmigiano?lock=69', 'activo', 4),
  ('Entrecote di Vacca alla Piastra', 'Entrecot de lomo bajo de vaca a la plancha', 22.00, 'https://loremflickr.com/400/300/entrecote,grilled,steak?lock=70', 'activo', 4),
  ('Cotoletta di Pollo con Patate Fritte', 'Filetes de pechuga de pollo empanados con patatas fritas', 14.00, 'https://loremflickr.com/400/300/chicken,milanesa,fries?lock=71', 'activo', 4),
  ('Tonno Rosso di Tarifa', 'Atún Rojo Mackintosh de Tarifa a la plancha', 24.00, 'https://loremflickr.com/400/300/tuna,grilled,red?lock=72', 'activo', 4),
  ('Tagliata di Vacca Tartufo e Porcini', 'Lomo bajo de vaca fileteado con trufa y setas Boletus', 23.00, 'https://loremflickr.com/400/300/beef,truffle,porcini?lock=73', 'activo', 4),
  ('Calamaro alla Piastra', 'Calamar de potera a la plancha con salsa verde', 21.00, 'https://loremflickr.com/400/300/grilled,squid,green?lock=74', 'activo', 4),
  ('Tentacolo di Polpo alla Griglia', 'Pata de pulpo cocida a baja temperatura y rematada a la parrilla', 20.00, 'https://loremflickr.com/400/300/octopus,grilled,tentacle?lock=75', 'activo', 4),
  ('Filetto di Vacca al Pepe Verde', 'Solomillo de vaca con salsa de pimienta verde', 25.00, 'https://loremflickr.com/400/300/filet,green,pepper?lock=76', 'activo', 4),
  ('Filetto di Vacca al Gorgonzola e Funghi', 'Solomillo de vaca con salsa de Gorgonzola y setas', 25.00, 'https://loremflickr.com/400/300/filet,gorgonzola,mushroom?lock=77', 'activo', 4),
  ('Panna Cotta con Frutti del Bosco', 'Nata cocida con vainilla natural y salsa de frutas del bosque', 5.00, 'https://loremflickr.com/400/300/pannacotta,berries?lock=78', 'activo', 5),
  ('Tiramisú della Casa', 'Galletas Savoiardi mojadas en café con crema de mascarpone y huevos', 5.00, 'https://loremflickr.com/400/300/tiramisu,mascarpone?lock=79', 'activo', 5),
  ('Cheesecake', 'Tarta de queso cocida al horno con salsa de frutos del bosque', 5.00, 'https://loremflickr.com/400/300/cheesecake,berries?lock=80', 'activo', 5),
  ('Nodini Fritti con Nutella e Pistacchio', 'Palitos de masa fritos con Nutella y crema de pistacho (3-4 personas)', 11.00, 'https://loremflickr.com/400/300/fried,dough,nutella?lock=81', 'activo', 5),
  ('Cannolo Siciliano', 'Masa crujiente rellena de crema de ricotta', 5.00, 'https://loremflickr.com/400/300/cannolo,sicilian,ricotta?lock=82', 'activo', 5),
  ('Torta Fondant al Cioccolato', 'Tarta de chocolate cremoso con helado de pistacho', 5.00, 'https://loremflickr.com/400/300/chocolate,fondant,cake?lock=83', 'activo', 5),
  ('Tiramisú al Pistacchio', 'Tiramisú con crema de mascarpone y pistacho dulce', 6.00, 'https://loremflickr.com/400/300/tiramisu,pistachio?lock=84', 'activo', 5),
  ('Rosso della Casa (copa)', 'Vino tinto de la casa - copa', 3.00, 'https://loremflickr.com/400/300/red,wine,glass?lock=85', 'activo', 6),
  ('Rosso della Casa (1/2 L)', 'Vino tinto de la casa - 1/2 litro', 8.50, 'https://loremflickr.com/400/300/red,wine,carafe?lock=86', 'activo', 6),
  ('Rosso della Casa (1 L)', 'Vino tinto de la casa - 1 litro', 12.00, 'https://loremflickr.com/400/300/red,wine,carafe?lock=87', 'activo', 6),
  ('Lambrusco Rosso', 'Lambrusco Rosso - Italia', 19.00, 'https://loremflickr.com/400/300/lambrusco,wine,italy?lock=88', 'activo', 6),
  ('Primitivo di Manduria', 'Primitivo di Manduria - Italia', 24.00, 'https://loremflickr.com/400/300/primitivo,wine,puglia?lock=89', 'activo', 6),
  ('Chianti Gallo Nero', 'Chianti Gallo Nero - Italia', 22.00, 'https://loremflickr.com/400/300/chianti,wine,tuscany?lock=90', 'activo', 6),
  ('Amarone della Valpolicella', 'Amarone della Valpolicella - Italia', 50.00, 'https://loremflickr.com/400/300/amarone,wine,italy?lock=91', 'activo', 6),
  ('Brunello di Montalcino', 'Brunello di Montalcino - Italia', 55.00, 'https://loremflickr.com/400/300/brunello,wine,montalcino?lock=92', 'activo', 6),
  ('Vetusta Ribera del Duero', 'Vetusta vino ecológico Ribera del Duero - España', 19.00, 'https://loremflickr.com/400/300/ribera,wine,spain?lock=93', 'activo', 6),
  ('Pagos de Valcerracin Roble', 'Pagos de Valcerracin roble Ribera del Duero - España', 19.50, 'https://loremflickr.com/400/300/ribera,wine,oak?lock=94', 'activo', 6),
  ('Pagos Anguix Ribera del Duero', 'Pagos Anguix Ribera del Duero - España', 33.00, 'https://loremflickr.com/400/300/ribera,wine,duero?lock=95', 'activo', 6),
  ('Viuda Negra Crianza Rioja', 'Viuda Negra crianza Rioja - España', 20.00, 'https://loremflickr.com/400/300/rioja,wine,crianza?lock=96', 'activo', 6),
  ('Tesalia Tierra de Cádiz', 'Tesalia Tierra de Cádiz - España', 40.00, 'https://loremflickr.com/400/300/tesalia,wine,cadiz?lock=97', 'activo', 6),
  ('Rosato della Casa (copa)', 'Vino rosado de la casa - copa', 3.00, 'https://loremflickr.com/400/300/rose,wine,glass?lock=98', 'activo', 6),
  ('Lambrusco Rosato', 'Lambrusco Rosato - Italia', 19.00, 'https://loremflickr.com/400/300/lambrusco,rose,italy?lock=99', 'activo', 6),
  ('Bianco della Casa (copa)', 'Vino blanco de la casa - copa', 3.00, 'https://loremflickr.com/400/300/white,wine,glass?lock=100', 'activo', 6),
  ('Sauvignon Colli Orientali del Friuli', 'Sauvignon dei Colli Orientali del Friuli - Italia', 18.00, 'https://loremflickr.com/400/300/sauvignon,wine,friuli?lock=101', 'activo', 6),
  ('Pinot Grigio Colli Orientali del Friuli', 'Pinot Grigio dei Colli Orientali del Friuli - Italia', 18.00, 'https://loremflickr.com/400/300/pinotgrigio,wine,friuli?lock=102', 'activo', 6),
  ('Prosecco Treviso Extra Dry', 'Prosecco Treviso millesimato extra dry - Italia', 19.00, 'https://loremflickr.com/400/300/prosecco,sparkling,wine?lock=103', 'activo', 6),
  ('Moscato Frizzante Viña Tendida', 'Moscato frizzante Viña Tendida - España', 14.00, 'https://loremflickr.com/400/300/moscato,sparkling,spain?lock=104', 'activo', 6),
  ('Spumante Ribolla Gialla', 'Spumante Ribolla Gialla dei Colli Orientali del Friuli - Italia', 21.00, 'https://loremflickr.com/400/300/ribolla,sparkling,italy?lock=105', 'activo', 6),
  ('Cerveza Estrella Galicia Barril 0.35L', 'Cerveza de barril Estrella Galicia 0,35 L', 2.50, 'https://loremflickr.com/400/300/estrella,beer,draft?lock=106', 'activo', 6),
  ('Cerveza Estrella Galicia Barril 0.50L', 'Cerveza de barril Estrella Galicia 0,50 L', 3.50, 'https://loremflickr.com/400/300/beer,draft,glass?lock=107', 'activo', 6),
  ('Nastro Azzurro', 'Cerveza Nastro Azzurro 0,33 L - Italia', 3.50, 'https://loremflickr.com/400/300/nastroazzurro,beer,italy?lock=108', 'activo', 6),
  ('Estrella Galicia Botella', 'Estrella Galicia botella 0,33 L', 3.00, 'https://loremflickr.com/400/300/estrella,beer,bottle?lock=109', 'activo', 6),
  ('Estrella Galicia sin Gluten', 'Estrella Galicia sin gluten 0,25 L', 3.50, 'https://loremflickr.com/400/300/beer,glutenfree,bottle?lock=110', 'activo', 6),
  ('Alhambra Reserva 1925', 'Alhambra Reserva 1925 0,33 L', 3.50, 'https://loremflickr.com/400/300/alhambra,beer,bottle?lock=111', 'activo', 6),
  ('Corona', 'Cerveza Corona 0,33 L - México', 4.00, 'https://loremflickr.com/400/300/corona,beer,mexico?lock=112', 'activo', 6),
  ('Dos Mares IPA', 'Dos Mares IPA artesanal de Tarifa 0,33 L', 4.00, 'https://loremflickr.com/400/300/ipa,craft,beer?lock=113', 'activo', 6),
  ('Dos Mares Irish Red', 'Dos Mares Irish Red artesanal de Tarifa 0,33 L', 4.00, 'https://loremflickr.com/400/300/red,ale,craft?lock=114', 'activo', 6),
  ('Franziskaner Weissbier', 'Franziskaner Weissbier 0,5 L - Alemania', 5.00, 'https://loremflickr.com/400/300/weissbier,franziskaner,beer?lock=115', 'activo', 6),
  ('Estrella Galicia Tostada 0.0', 'Estrella Galicia tostada 0,0 sin alcohol 0,25 L', 2.50, 'https://loremflickr.com/400/300/beer,toasted,alcoholfree?lock=116', 'activo', 6),
  ('Estrella Galicia 0.0', 'Estrella Galicia 0,0 sin alcohol 0,25 L', 2.50, 'https://loremflickr.com/400/300/beer,alcoholfree,light?lock=117', 'activo', 6),
  ('Caffè Espresso', 'Café espresso o largo', 1.50, 'https://loremflickr.com/400/300/espresso,coffee,italian?lock=118', 'activo', 6),
  ('Amaro Italiano (solo)', 'Averna, Montenegro, Fernet Branca, Grappa, Limoncello, Sambuca... (solo)', 5.00, 'https://loremflickr.com/400/300/amaro,liquor,italian?lock=119', 'activo', 6),
  ('Amaro Italiano (combinado)', 'Amaros italianos en combinado', 7.00, 'https://loremflickr.com/400/300/cocktail,amaro,italian?lock=120', 'activo', 6);
